name: Scrape & Evaluate Premier League Standings

on:
    schedule:
      - cron: "0 7 * * *"
    workflow_dispatch:

permissions:
  contents: write

jobs:
    run-script:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
              with:
                token: ${{ secrets.YML_TOKEN }}

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.x'

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            - name: Run scrape_standings.py
              env:
                LEAGUE: "prem"
              run: python scrape_standings.py

            - name: Push all changes
              run: |
                git pull
                git config --global user.name "github-actions"
                git config --global user.email "github-actions@github.com"
                git add .
                git commit -m "Scrape standings"
                git push https://x-access-token:${{ secrets.YML_TOKEN }}@github.com/${{ github.repository }} HEAD:main
