name: Send NBA Results by Email

on:
    # schedule:
    #   - cron: '0 16 * * 1'
    workflow_dispatch:

jobs:
    send-results:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.x'

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            - name: Run send_results_nba.py
              env:
                GMAIL_USERNAME: ${{ secrets.GMAIL_USERNAME }}
                GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
              run: python send_results_nba.py